= jOOQ: Database Abstractions Without Distractions

== Introduction

This repository contains the source both the slides and demonstration application for this presentation. This document will describe the repository and explain how to (re)use any of the content you find here.

== The Slides

The slides for the presentation were written using the shower.js library. To build and view the slides as presented, execute the following commands:

[source,bash]
-----
$ cd slides
$ npm install
$ bash serve.sh
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:9090
    External: http://192.168.1.26:9090
 --------------------------------------
          UI: http://localhost:9091
 UI External: http://localhost:9091
 --------------------------------------
-----

You can now view the http://localhost:9090[slides] in your browser. Click on title slide to view it full-sized, then use the left and right arrows to navigate backward and forward. For more advanced uses, please see the shower.js documentation.

== The Demo App

All dependencies required by the demos should be downloaded and installed by Maven, so building should be straightforward for any Maven users. Gradle users truly are on their own here. :)

The demos used in the presentation were written as unit tests to make them easier to run. This also avoids unnecessarily complicating the demos with frameworks that some may be unfamiliar with. If you're not familiar with unit tests or JUnit, please go take care of that first. ;)

The lone exception to this is the "conditional conditions" demo, which is not covered in the slides (there's a slide, but it was commented out for time's sake), which is a Quarkus-based REST endpoint. To see that in action, do the following:

[source,bash]
-----
$ cd codegen-demo
$ mvn clean install quarkus:dev
# In another terminal...
$ http :8080/nocondition
...
$ http :8080/nocondition?lastName=SNYDER
...
-----

== Questions?

If you happen to have questions, please feel free to find me on https://twitter.com/jasondlee[Twitter]. I'd love to discuss and help.
